name: Upstream Release Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

env:
  UPSTREAM: pelican-dev/wings

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream and fetch tags
        run: |
            git remote add upstream https://github.com/${{ env.UPSTREAM }}.git
            git fetch upstream --tags

      - name: Get latest upstream tag
        id: tag
        run: |
            UPSTREAM_TAG=$(git ls-remote --tags upstream | awk -F/ '{print $NF}' | sort -V | tail -n1)
            LOCAL_TAG=$(git tag -l | sort -V | tail -n1 || echo "")
            echo "upstream=$UPSTREAM_TAG" >> $GITHUB_OUTPUT
            echo "local=$LOCAL_TAG" >> $GITHUB_OUTPUT
            if [ "$UPSTREAM_TAG" != "$LOCAL_TAG" ]; then
                echo "update_needed=true" >> $GITHUB_OUTPUT
            else
                echo "update_needed=false" >> $GITHUB_OUTPUT
            fi

      - name: Push upstream tag to origin
        if: steps.tag.outputs.update_needed == 'true'
        run: |
            NEW_TAG=${{ steps.tag.outputs.upstream }}
            git push origin "$NEW_TAG"

  release:
      needs: sync
      if: needs.sync.outputs.update_needed == 'true'
      uses: ./.github/workflows/release.yaml
